import type { Metadata } from "next";

import { Content, PageContainer } from "@/components/Footer/FooterStyles";
import MainNavigation from "@/components/Header/MainNavigation";
import QueryClientWrapper from "@/components/Shared/QueryClient/QueryClientProvider";
import AuthProvider from "@/context/auth-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryClientWrapper>
          <AuthProvider>
            <PageContainer>
              <Content>
                <MainNavigation />
                {children}
              </Content>
            </PageContainer>
          </AuthProvider>
        </QueryClientWrapper>
      </body>
    </html>
  );
}
