import type { Metadata } from "next";

import { Content, PageContainer } from "@/components/Footer/FooterStyles";
import MainNavigation from "@/components/Header/MainNavigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PageContainer>
          <Content>
            <MainNavigation />
            {children}
          </Content>
        </PageContainer>
      </body>
    </html>
  );
}
