import type { Metadata } from "next";

import { Content, PageContainer } from "@/components/Footer/FooterStyles";
import MainNavigation from "@/components/Header/MainNavigation";
import QueryClientWrapper from "@/components/Shared/QueryClient/QueryClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryClientWrapper>
          <PageContainer>
            <Content>
              <MainNavigation />
              {children}
            </Content>
          </PageContainer>
        </QueryClientWrapper>
      </body>
    </html>
  );
}
